import type { APIRoute } from "astro";
type RuntimeEnv = Record<string, any>;
const text = (value: unknown) => typeof value === "string" ? value.trim().slice(0, 2_000) : "";
const sha256 = async (value: string) => Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256", new TextEncoder().encode(value.trim().toLowerCase())))).map(byte => byte.toString(16).padStart(2, "0")).join("");
async function authorized(request: Request, expected: string) {
  const actual = request.headers.get("authorization")?.replace(/^Bearer\s+/i, "") ?? "";
  if (!actual || !expected) return false;
  const [left, right] = await Promise.all([sha256(actual), sha256(expected)]);
  return left === right;
}
export const POST: APIRoute = async ({ request, locals }) => {
  if (Number(request.headers.get("content-length") || 0) > 65_536) return new Response(null, { status: 413 });
  if (!request.headers.get("content-type")?.toLowerCase().startsWith("application/json")) return new Response(null, { status: 415 });
  const env = ((locals as any).runtime?.env ?? {}) as RuntimeEnv;
  if (!(await authorized(request, text(env.STAGE_WEBHOOK_SECRET)))) return new Response(null, { status: 401 });
  if (!env.FUNNEL_DB || !env.META_PIXEL_ID || !env.META_CAPI_ACCESS_TOKEN) return new Response(null, { status: 503 });
  const payload = await request.json().catch(() => null) as any;
  const leadUuid = text(payload?.leadUuid);
  const stage = text(payload?.stage);
  const mappings: Record<string, string> = { qualified: "QualifiedLead", appointment: "Schedule", show: "Showed", sale: "Purchase" };
  const eventName = mappings[stage];
  if (!/^[0-9a-f-]{36}$/i.test(leadUuid) || !eventName) return new Response(null, { status: 400 });
  const value = Number(payload?.value);
  if (stage === "sale" && (!Number.isFinite(value) || value <= 0)) return new Response(null, { status: 422 });
  await env.FUNNEL_DB.prepare("CREATE TABLE IF NOT EXISTS funnel_leads (lead_uuid TEXT PRIMARY KEY, first_event_id TEXT NOT NULL, first_url TEXT NOT NULL, original_query_string TEXT NOT NULL, fbc TEXT, fbp TEXT, ip_address TEXT, user_agent TEXT, email_hash TEXT, phone_hash TEXT, first_name_hash TEXT, last_name_hash TEXT, created_at TEXT NOT NULL)").run();
  await env.FUNNEL_DB.prepare("CREATE TABLE IF NOT EXISTS downstream_conversions (external_id TEXT PRIMARY KEY, event_id TEXT UNIQUE NOT NULL, lead_uuid TEXT NOT NULL, stage TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'pending', created_at TEXT NOT NULL, sent_at TEXT)").run();
  const lead = await env.FUNNEL_DB.prepare("SELECT * FROM funnel_leads WHERE lead_uuid = ?").bind(leadUuid).first();
  if (!lead) return new Response(null, { status: 404 });
  const externalId = leadUuid + ":" + stage;
  const eventId = text(payload?.eventId) || await sha256(externalId);
  await env.FUNNEL_DB.prepare("INSERT OR IGNORE INTO downstream_conversions (external_id, event_id, lead_uuid, stage, status, created_at) VALUES (?, ?, ?, ?, 'pending', ?)").bind(externalId, eventId, leadUuid, stage, new Date().toISOString()).run();
  const conversion = await env.FUNNEL_DB.prepare("SELECT status, event_id FROM downstream_conversions WHERE external_id = ?").bind(externalId).first();
  if (conversion?.status === "sent") return new Response(null, { status: 202 });
  const user_data: Record<string, unknown> = { external_id: [await sha256(leadUuid)] };
  if (lead.fbc) user_data.fbc = lead.fbc;
  if (lead.fbp) user_data.fbp = lead.fbp;
  if (lead.ip_address) user_data.client_ip_address = lead.ip_address;
  if (lead.user_agent) user_data.client_user_agent = lead.user_agent;
  if (lead.email_hash) user_data.em = [lead.email_hash];
  if (lead.phone_hash) user_data.ph = [lead.phone_hash];
  if (lead.first_name_hash) user_data.fn = [lead.first_name_hash];
  if (lead.last_name_hash) user_data.ln = [lead.last_name_hash];
  const version = /^v\d+\.\d+$/.test(text(env.META_GRAPH_API_VERSION)) ? text(env.META_GRAPH_API_VERSION) : "v26.0";
  const custom_data: Record<string, unknown> = { stage, first_url: lead.first_url, original_query_string: lead.original_query_string };
  const configuredValues: Record<string, unknown> = { qualified: env.META_VALUE_QUALIFIED, appointment: env.META_VALUE_SCHEDULE, show: env.META_VALUE_SHOWED };
  const configuredValue = Number(configuredValues[stage]);
  if (stage === "sale") custom_data.value = value;
  else if (Number.isFinite(configuredValue) && configuredValue >= 0) custom_data.value = configuredValue;
  if (custom_data.value !== undefined) custom_data.currency = text(payload?.currency) || "USD";
  const response = await fetch(`https://graph.facebook.com/${version}/${env.META_PIXEL_ID}/events`, { method: "POST", headers: { authorization: `Bearer ${env.META_CAPI_ACCESS_TOKEN}`, "content-type": "application/json" }, body: JSON.stringify({ data: [{ event_name: eventName, event_time: Math.floor(Date.now() / 1000), event_id: conversion?.event_id || eventId, action_source: "website", event_source_url: lead.first_url, user_data, custom_data }] }) });
  if (!response.ok) return new Response(null, { status: 502 });
  await env.FUNNEL_DB.prepare("UPDATE downstream_conversions SET status = 'sent', sent_at = ? WHERE external_id = ?").bind(new Date().toISOString(), externalId).run();
  return new Response(null, { status: 202 });
};
